datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
# persistence:
#   type: pvc
#   enabled: true
#   # storageClassName: default
#   accessModes:
#     - ReadWriteOnce
#   size: 3Gi
#   # annotations: {}
#   finalizers:
#     - kubernetes.io/pvc-protection
#   # selectorLabels: {}
#   ## Sub-directory of the PV to mount. Can be templated.
#   # subPath: ""
#   ## Name of an existing PVC. Can be templated.
#   # existingClaim:
#   ## Extra labels to apply to a PVC.
#   extraPvcLabels: {}
