## https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml#L502
## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file#config_section
logLevel: warn # Allowed values are: off, error, warn, info, debug and trace.

config:
  # service: |
  #   [SERVICE]
  #       Daemon Off
  #       Flush {{ .Values.flush }}
  #       Log_Level {{ .Values.logLevel }}
  #       Parsers_File /fluent-bit/etc/parsers.conf
  #       Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
  #       HTTP_Server On
  #       HTTP_Listen 0.0.0.0
  #       HTTP_Port {{ .Values.metricsPort }}
  #       Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        # Parser cri
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        # Merge_Log_Key original_log
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        # Namespace_Labels On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  ## https://docs.fluentbit.io/manual/pipeline/outputs/opentelemetry
  outputs: |
    [OUTPUT]
        Name opentelemetry
        Match kube.*
        Host collector
        Port 3030
        metrics_uri /v1/metrics
        logs_uri /v1/logs
        traces_uri /v1/traces
        Log_response_payload True
        tls off
        tls.verify off
        Retry_Limit False
        add_label app fluent-bit
        add_label color blue

    [OUTPUT]
        Name opentelemetry
        Match host.*
        Host collector
        Port 3030
        metrics_uri /v1/metrics
        logs_uri /v1/logs
        traces_uri /v1/traces
        Log_response_payload True
        tls off
        tls.verify off
        Retry_Limit False

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  # customParsers: |
  #   [PARSER]
  #       Name docker_no_time
  #       Format json
  #       Time_Keep Off
  #       Time_Key time
  #       Time_Format %Y-%m-%dT%H:%M:%S.%L
